server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name powerbankrental.tw1.ru 45.93.201.139 _;

    root /var/www/powerbank-rental/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
